library: ~/Dropbox/Musique/library.blb
directory: ~/Dropbox/Musique
plugins: inline info fetchart ftintitle

ignore: ._* .AppleDouble .DS_Store
asciify_paths: yes
threaded: yes
art_filename: cover
per_disc_numbering: yes
sort_case_insensitive: yes
max_filename_length: 64

import:
  resume: ask
  quiet_fallback: skip
  
paths:
  default: ${albumartist}/${album}%aunique{}/%if{${multidisc},${disc}-}${track}.${title}
  comp: ${albumartist}/${album}%aunique{}/%if{${multidisc},${disc}-}${track}.${title}
  singleton: Singletons/${artist} - ${title}
  
fetchart:
    maxwidth: 1200
    sources:
        - filesystem
        - coverart: release
        - itunes
        - coverart: releasegroup
        - '*'
  
ftintitle:
  auto: yes
  format: '[feat. {0}]'